### ISSUE TITLE
How to use fonts offline?

### ISSUE THREAD

**Issue by tariksetia** [matfax/kivysome#39]
I am building an app which will run on servers with no internet connectivity.
How can I make Kivysome to pick fonts locally?

**Comment by matfax** [comment]
This matter has been solved in #16 and #18.
Kivysome will not require internet access if the fonts matching the pinned version are provided.

For instance, if you pin the `FontGroup.REGULAR` version `5.13.1` (instead of `LATEST`), then there need to exist two files in the project folder:
* `fonts/fa-regular-5.13.1.ttf`
* `fonts/fa-regular-5.13.1.css`

Ideally, the `fontd` file should also exist. It is normally created during the first execution.
To create it manually, execute `create_fontdict_file("fonts/fa-regular-5.13.1.css", "fonts/fa-regular-5.13.1.fontd")` imported from `kivysome.iconfonts`.

**Comment by tariksetia** [comment]
Thanks for the information !!😀
